language: node_js
node_js:
  - "12.16.2"

cache:
  directories:
    - "node_modules"
services:
  - postgresql  

before_script:
  - psql -c "create database test_env ;" -U postgres
  
script:
  - npm run devtable 
  - npm test
  
after_success:
  - npm run coverage
